### ISSUE TITLE
Pick time and location for 2018 in-person AGM

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#61]
As mentioned at our March Coordinating Call, we gotta get going on picking our next in-person summer-time longer-format AGM!

To aid us in that I'm asking people to do 2 things:

1. Update [this calendar](https://calendar.google.com/calendar?cid=YmJiNW1xOTQzMDQ5NW81bTJjcXRpdm1sNTRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) with their unavailability from **JUN-MID SEPTEMBER** (many of you should have access through the google group, let me know if not!)

2. Brainstorm potential locations *in this issue*

We'll settle on a time at our Spring Coordinating Call 🌷

--- 

Potential Locations:
(I'll edit and update this list)

- Toronto (especially if co-located with EDGI meeting, Our Networks 🎛 )
- New York (especially if co-located with EDGI meeting)
- Bay Area ?? (potential co-location?)
- **PHILADELPHIA** 📣 (enthusiasm)

**Comment by mhucka** [comment]
Just to note some upcoming meetings some people might be attending and so might be opportunities for co-location:

• [JCDL 2018](https://2018.jcdl.org) – June 3–6 in Fort Worth, TX
• [DLF 2018](https://forum2018.diglib.org) – October in Vegas
• [IIPC Web Archiving conference 2018](http://netpreserve.org/ga2018/) – Nov 12–15 in Wellington, New Zealand

**Comment by jessogden** [comment]
My summer schedule is really really up in the air right now, but hoping things will become clearer in next couple of weeks so I can update the cal. I too am supposed to be making a major PhD push so that may impact my ability to travel but am hopeful :-) 

Other events that I may be at this year: 
- [Data Justice](https://datajusticelab.org/data-justice-conference/data-justice-2018/) - May 21-22 in Cardiff, UK (too soon and far for most I expect!)
- [4S 2018](https://4s2018sydney.org/) - Aug 29-Sept 1 in Sydney, Australia 
- [AoIR 2018](https://aoir.org/aoir2018/) - Oct 10-13 in Montreal, Canada

**Comment by jessogden** [comment]
Follow-up message from today's ALL EDGI mtg - there's no timeline yet but the current cities being considered for the next in-person EDGI mtg (just in case DT wants to co-locate):
- Bay Area, CA
- New York, NY
- Stony Brook, NY (arg cheaper than NYC but close)
- Toronto, Canada

**Comment by dcwalk** [comment]
Yeah! We talked about co-locating and I think that would be a good goal!

**Comment by dcwalk** [comment]
- We have a time: August 27-30
- We have a place (priority order):
  1. co-located with EDGI meeting in Toronto/NY
  2. Philly!

So I'm closing this as done! We're just waiting on the EDGI decision to pin down :) @titaniumbones and @dcwalk are on the organizing committee for the meeting, an issue is in #63
